### ISSUE TITLE
UI/UX: 底栏高度太低，不容易点到

### ISSUE THREAD

**Issue by lideming** [guet1024/GUET-Schedule-Open#1]
建议增大底栏的上下边距，虽然如果没有图标会比较奇怪……
![image](https://user-images.githubusercontent.com/14901890/103204807-1a663e00-4933-11eb-9a4f-d57b688e883e.png)

**Comment by TelephoneTan** [comment]
好的

**Comment by TelephoneTan** [comment]
已解决~
