### ISSUE TITLE
课程表

### ISSUE THREAD

**Issue by Higgins995** [guet1024/GUET-Schedule-Open#2]
我认为可以在周课表界面左侧或者右侧 添加上课时间和下课时间

**Comment by TelephoneTan** [comment]
嗯，后面会加这个功能











***@***.***)

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月20日(周二) 晚上7:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [guet1024/GUET-Schedule-Open] 课程表 (#2)




 
我认为可以在周课表界面左侧或者右侧 添加上课时间和下课时间

**Comment by TelephoneTan** [comment]
已解决~
