### ISSUE TITLE
guet课程表不兼容鸿蒙os系统的问题

### ISSUE THREAD

**Issue by RuoMengAwA** [guet1024/GUET-Schedule-Open#3]
# 具体相关信息
**机型**：华为p20
**系统**：鸿蒙os
**使用状况**：打开guet课程表后即闪退，在更新鸿蒙推送之前可正常打开使用

**Comment by TelephoneTan** [comment]
感谢你的反馈，我会尽快修复这个bug









***@***.***)

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月18日(周三) 晚上9:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [guet1024/GUET-Schedule-Open] guet课程表不兼容鸿蒙os系统的问题 (#3)




 
具体相关信息
 
机型：华为p20
 系统：鸿蒙os
 使用状况：打开guet课程表后即闪退，在更新鸿蒙推送之前可正常打开使用

**Comment by RuoMengAwA** [comment]
非常感谢作者，现在我已经修复这个bug了，同时发现了两点意外状况：原安卓手机更新鸿蒙推送后guet课程表可能会受到损坏，导致闪退，需要卸载重装，且在登录时，若学分系统密码验证步骤中开了梯子，则会弹出用户名或密码错误的选项

**Comment by TelephoneTan** [comment]
按照你的描述，这可能是鸿蒙系统的原因，我会进一步排查。如果出现用户名或密码错误的提示，几乎可以肯定是用户名或密码错误。









***@***.***)

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月19日(周四) 凌晨0:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guet1024/GUET-Schedule-Open] guet课程表不兼容鸿蒙os系统的问题 (#3)




 
非常感谢作者，现在我已经修复这个bug了，同时发现了两点意外状况：原安卓手机更新鸿蒙推送后guet课程表可能会受到损坏，导致闪退，需要卸载重装，且在登录时，若学分系统密码验证步骤中开了梯子，则会弹出用户名或密码错误的选项
